spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.168.1.209:33075/wutbiolab?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Gooalgene@33075
    type: com.zaxxer.hikari.HikariDataSource
  http:
    encoding:
      charset: UTF-8
